import { useState } from 'react';
import { RefreshCw, Key, Lock, Unlock, ChevronRight, CheckCircle } from 'lucide-react';

// Modulus q used for Baby-Kyber demonstration (small prime for educational purposes)
const Q = 17;

// --- TypeScript types ---
type Matrix = number[][];  // 2D matrix of integers
type Vector = number[];    // Column vector of integers

// --- Utility: modular arithmetic ---
/** Returns x mod q, always non-negative */
const mod = (x: number, q: number): number => ((x % q) + q) % q;

/** Scalar multiplication of a matrix and a vector, reduced mod q */
const matVecMul = (A: Matrix, v: Vector, q: number): Vector =>
  A.map((row) => mod(row.reduce((acc, aij, j) => acc + aij * v[j], 0), q));

/** Element-wise addition of two vectors, reduced mod q */
const vecAdd = (a: Vector, b: Vector, q: number): Vector =>
  a.map((ai, i) => mod(ai + b[i], q));

/** Element-wise subtraction of two vectors, reduced mod q */
const vecSub = (a: Vector, b: Vector, q: number): Vector =>
  a.map((ai, i) => mod(ai - b[i], q));

// --- Key generation helpers ---
/** Generates a random n×n matrix of integers in [0, q-1] */
const randomMatrix = (n: number, q: number): Matrix =>
  Array.from({ length: n }, () =>
    Array.from({ length: n }, () => Math.floor(Math.random() * q))
  );

/** Generates a random vector of small integers in [0, 2] (small secret/error) */
const randomSmallVector = (n: number): Vector =>
  Array.from({ length: n }, () => Math.floor(Math.random() * 3)); // values: 0, 1 or 2

/** Generates a random message bit vector of length n in {0, ⌊q/2⌋} */
const randomMessage = (n: number, q: number): Vector =>
  Array.from({ length: n }, () => (Math.random() > 0.5 ? Math.floor(q / 2) : 0));

// --- Display helpers ---
const matrixToString = (m: Matrix): string =>
  m.map((row) => `[${row.join(', ')}]`).join('\n');

const vectorToString = (v: Vector): string => `[${v.join(', ')}]`;

// --- State types ---
interface KeyPair {
  A: Matrix;   // Public random matrix (generated by key generation)
  s: Vector;   // Secret key (small random vector)
  e: Vector;   // Error vector (small random vector, added to harden LWE)
  t: Vector;   // Public key: t = A·s + e (mod q)
}

interface Ciphertext {
  u: Vector;   // u = A^T·r + e1 (mod q)
  v: Vector;   // v = t^T·r + e2 + message (mod q)
  e1: Vector;  // Encapsulation error vector 1
  e2: Vector;  // Encapsulation error vector 2
  r: Vector;   // Random encapsulation vector
}

interface SimulatorState {
  keyPair: KeyPair | null;
  message: Vector | null;
  ciphertext: Ciphertext | null;
  decrypted: Vector | null;
  step: 0 | 1 | 2 | 3;  // 0=initial, 1=keys generated, 2=encapsulated, 3=decapsulated
}

// --- Sub-components ---
interface CardProps {
  title: string;
  subtitle?: string;
  icon: React.ReactNode;
  active?: boolean;
  done?: boolean;
  children: React.ReactNode;
}

const StepCard: React.FC<CardProps> = ({ title, subtitle, icon, active, done, children }) => (
  <div
    className={`rounded-xl border p-5 transition-all ${
      done
        ? 'border-green-400 dark:border-green-600 bg-green-50 dark:bg-green-900/20'
        : active
        ? 'border-blue-400 dark:border-blue-600 bg-blue-50 dark:bg-blue-900/20 shadow-md'
        : 'border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-800'
    }`}
  >
    <div className="flex items-center gap-3 mb-3">
      <span
        className={`p-2 rounded-lg ${
          done
            ? 'bg-green-100 dark:bg-green-800 text-green-600 dark:text-green-300'
            : active
            ? 'bg-blue-100 dark:bg-blue-800 text-blue-600 dark:text-blue-300'
            : 'bg-slate-100 dark:bg-slate-700 text-slate-500 dark:text-slate-400'
        }`}
      >
        {done ? <CheckCircle size={18} /> : icon}
      </span>
      <div>
        <h3 className="font-semibold text-slate-800 dark:text-slate-100 text-sm">{title}</h3>
        {subtitle && <p className="text-xs text-slate-500 dark:text-slate-400">{subtitle}</p>}
      </div>
    </div>
    {children}
  </div>
);

interface CodeBlockProps {
  label: string;
  value: string;
}

const CodeBlock: React.FC<CodeBlockProps> = ({ label, value }) => (
  <div className="mb-2">
    <span className="text-xs font-semibold text-slate-500 dark:text-slate-400 uppercase tracking-wide">
      {label}
    </span>
    <pre className="mt-1 text-xs bg-slate-100 dark:bg-slate-900 rounded p-2 overflow-x-auto text-slate-700 dark:text-slate-300 font-mono whitespace-pre-wrap">
      {value}
    </pre>
  </div>
);

// --- Main simulator component ---
const MLKEMSimulator: React.FC = () => {
  const [state, setState] = useState<SimulatorState>({
    keyPair: null,
    message: null,
    ciphertext: null,
    decrypted: null,
    step: 0,
  });

  // --- Step 1: Key Generation ---
  // Simulates the key generation phase of ML-KEM (Baby-Kyber):
  //   Public key: t = A·s + e  (mod q)   — hardness relies on LWE problem
  //   Private key: s
  const handleKeyGen = () => {
    const A = randomMatrix(2, Q);          // Public random matrix A ∈ Z_q^{2x2}
    const s = randomSmallVector(2);        // Secret key s ∈ {0,1,2}^2 (small)
    const e = randomSmallVector(2);        // Error vector e ∈ {0,1,2}^2 (small)
    const t = vecAdd(matVecMul(A, s, Q), e, Q); // Public key: t = As + e mod q

    setState({
      keyPair: { A, s, e, t },
      message: null,
      ciphertext: null,
      decrypted: null,
      step: 1,
    });
  };

  // --- Step 2: Encapsulation (Encryption) ---
  // The sender uses the public key (A, t) to encrypt a message m:
  //   u = A^T·r + e1  (mod q)
  //   v = t^T·r + e2 + m  (mod q)
  // The ciphertext is (u, v).
  const handleEncapsulate = () => {
    if (!state.keyPair) return;
    const { A, t } = state.keyPair;

    const r = randomSmallVector(2);        // Random encapsulation vector
    const e1 = randomSmallVector(2);       // Encapsulation error 1
    const e2 = randomSmallVector(2);       // Encapsulation error 2
    const message = randomMessage(2, Q);  // Random 2-bit message encoded as {0, ⌊q/2⌋}

    // u = A^T · r + e1 mod q
    const AT: Matrix = [[A[0][0], A[1][0]], [A[0][1], A[1][1]]]; // Transpose of A
    const u = vecAdd(matVecMul(AT, r, Q), e1, Q);

    // v = (t^T · r) · [1,1] + e2 + message  (mod q)
    // The shared secret t^T·r is computed as a scalar, broadcast to a vector,
    // then e2 and the encoded message are added element-wise.
    // This extends the standard Baby-Kyber scalar v to a 2-bit message vector.
    const tDotR = mod(t.reduce((acc, ti, i) => acc + ti * r[i], 0), Q);
    const tDotRVec: Vector = [tDotR, tDotR]; // broadcast shared secret to vector dimension
    const v = vecAdd(vecAdd(tDotRVec, e2, Q), message, Q);

    setState((prev) => ({
      ...prev,
      message,
      ciphertext: { u, v, e1, e2, r },
      decrypted: null,
      step: 2,
    }));
  };

  // --- Step 3: Decapsulation (Decryption) ---
  // The recipient uses the secret key s to recover the message:
  //   m' ≈ v - s^T·u  (mod q)
  // Then round each component: if close to ⌊q/2⌋ → 1, else → 0
  const handleDecapsulate = () => {
    if (!state.keyPair || !state.ciphertext) return;
    const { s } = state.keyPair;
    const { u, v } = state.ciphertext;

    // Compute s^T · u mod q  (dot product as scalar, applied to each v component)
    const sDotU = mod(s.reduce((acc, si, i) => acc + si * u[i], 0), Q);

    // m' = v - s^T·u mod q  (recover noisy message)
    const noisy = vecSub(v, [sDotU, sDotU], Q);

    // Round: values close to ⌊q/2⌋ = 8 decode to 1, values close to 0 decode to 0
    const halfQ = Math.floor(Q / 2);
    const decrypted: Vector = noisy.map((x) => {
      const distToHalf = Math.min(Math.abs(x - halfQ), Q - Math.abs(x - halfQ));
      const distToZero = Math.min(x, Q - x);
      return distToHalf < distToZero ? halfQ : 0;
    });

    setState((prev) => ({ ...prev, decrypted, step: 3 }));
  };

  const handleReset = () => {
    setState({ keyPair: null, message: null, ciphertext: null, decrypted: null, step: 0 });
  };

  const { keyPair, message, ciphertext, decrypted, step } = state;

  // Check if decryption was successful
  const decryptionSuccess =
    decrypted !== null &&
    message !== null &&
    decrypted.every((d, i) => d === message[i]);

  return (
    <div className="max-w-4xl mx-auto space-y-8">
      <header>
        <h2 className="text-3xl font-bold text-slate-800 dark:text-slate-100">
          Simulador ML-KEM (Baby-Kyber)
        </h2>
        <p className="mt-3 text-slate-600 dark:text-slate-400 text-lg leading-relaxed">
          Simulación simplificada del flujo de ML-KEM usando aritmética modular con{' '}
          <span className="font-mono bg-slate-100 dark:bg-slate-700 px-1 rounded">q = {Q}</span>.
          Este "Baby-Kyber" ilustra los pasos conceptuales sin la complejidad del estándar completo.
        </p>
      </header>

      {/* Parameter info */}
      <div className="flex flex-wrap gap-3">
        {[
          { label: 'Módulo q', value: Q.toString() },
          { label: 'Dimensión n', value: '2' },
          { label: 'Algoritmo', value: 'Baby-Kyber (educativo)' },
          { label: 'Problema base', value: 'Module-LWE' },
        ].map(({ label, value }) => (
          <div
            key={label}
            className="bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-lg px-4 py-2 shadow-sm"
          >
            <p className="text-xs text-slate-500 dark:text-slate-400">{label}</p>
            <p className="text-sm font-semibold text-slate-800 dark:text-slate-100">{value}</p>
          </div>
        ))}
      </div>

      {/* Step 1 – Key Generation */}
      <StepCard
        title="Paso 1 – Generación de Claves"
        subtitle="Genera la clave pública (A, t) y la clave secreta s"
        icon={<Key size={18} />}
        active={step === 0 || step === 1}
        done={step > 1}
      >
        <p className="text-xs text-slate-500 dark:text-slate-400 mb-3">
          <strong>Fórmula:</strong>{' '}
          <span className="font-mono bg-slate-100 dark:bg-slate-700 px-1 rounded">
            t = A · s + e (mod {Q})
          </span>{' '}
          — La seguridad se basa en la dificultad del problema LWE: dado (A, t), recuperar s es computacionalmente difícil.
        </p>

        {keyPair && (
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 mb-4">
            <CodeBlock label="Matriz pública A" value={matrixToString(keyPair.A)} />
            <div>
              <CodeBlock label="Clave secreta s (privada)" value={vectorToString(keyPair.s)} />
              <CodeBlock label="Vector error e" value={vectorToString(keyPair.e)} />
              <CodeBlock label="Clave pública t = As+e mod q" value={vectorToString(keyPair.t)} />
            </div>
          </div>
        )}

        <button
          onClick={handleKeyGen}
          className="flex items-center gap-2 px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white text-sm font-medium rounded-lg transition-colors"
        >
          <RefreshCw size={14} />
          {keyPair ? 'Regenerar Claves' : 'Generar Claves'}
        </button>
      </StepCard>

      {/* Step 2 – Encapsulation */}
      <StepCard
        title="Paso 2 – Encapsulamiento (Cifrado)"
        subtitle="Cifra un mensaje aleatorio usando la clave pública (A, t)"
        icon={<Lock size={18} />}
        active={step === 1 || step === 2}
        done={step > 2}
      >
        <p className="text-xs text-slate-500 dark:text-slate-400 mb-3">
          <strong>Fórmulas:</strong>{' '}
          <span className="font-mono bg-slate-100 dark:bg-slate-700 px-1 rounded">
            u = Aᵀ·r + e₁
          </span>{' '}
          y{' '}
          <span className="font-mono bg-slate-100 dark:bg-slate-700 px-1 rounded">
            v = tᵀ·r + e₂ + m
          </span>{' '}
          — El emisor añade ruido para ocultar el mensaje.
        </p>

        {ciphertext && message && (
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 mb-4">
            <div>
              <CodeBlock label="Mensaje original m" value={vectorToString(message)} />
              <CodeBlock label="Vector aleatorio r" value={vectorToString(ciphertext.r)} />
            </div>
            <div>
              <CodeBlock label="Criptograma u" value={vectorToString(ciphertext.u)} />
              <CodeBlock label="Criptograma v" value={vectorToString(ciphertext.v)} />
            </div>
          </div>
        )}

        <div className="flex items-center gap-2">
          <button
            onClick={handleEncapsulate}
            disabled={!keyPair}
            className="flex items-center gap-2 px-4 py-2 bg-purple-600 hover:bg-purple-700 disabled:opacity-40 disabled:cursor-not-allowed text-white text-sm font-medium rounded-lg transition-colors"
          >
            <ChevronRight size={14} />
            Encapsular Mensaje
          </button>
          {!keyPair && (
            <span className="text-xs text-amber-600 dark:text-amber-400">
              Genera las claves primero
            </span>
          )}
        </div>
      </StepCard>

      {/* Step 3 – Decapsulation */}
      <StepCard
        title="Paso 3 – Desencapsulamiento (Descifrado)"
        subtitle="Recupera el mensaje usando la clave secreta s"
        icon={<Unlock size={18} />}
        active={step === 2 || step === 3}
        done={step === 3 && decryptionSuccess}
      >
        <p className="text-xs text-slate-500 dark:text-slate-400 mb-3">
          <strong>Fórmula:</strong>{' '}
          <span className="font-mono bg-slate-100 dark:bg-slate-700 px-1 rounded">
            m' = v − sᵀ·u (mod {Q})
          </span>{' '}
          — Luego se redondea: valores próximos a ⌊q/2⌋={Math.floor(Q / 2)} → bit 1, próximos a 0 → bit 0.
        </p>

        {decrypted !== null && message !== null && (
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 mb-4">
            <CodeBlock label="Mensaje recuperado m'" value={vectorToString(decrypted)} />
            <CodeBlock label="Mensaje original m" value={vectorToString(message)} />
          </div>
        )}

        {step === 3 && (
          <div
            className={`flex items-center gap-2 p-3 rounded-lg mb-4 text-sm ${
              decryptionSuccess
                ? 'bg-green-100 dark:bg-green-900/30 text-green-700 dark:text-green-300 border border-green-300 dark:border-green-700'
                : 'bg-red-100 dark:bg-red-900/30 text-red-700 dark:text-red-300 border border-red-300 dark:border-red-700'
            }`}
          >
            <CheckCircle size={16} />
            {decryptionSuccess
              ? '✅ Descifrado correcto: m\' = m. ¡El esquema funciona!'
              : '⚠️ Error de descifrado: el ruido excedió la capacidad de corrección (normal con q pequeño).'}
          </div>
        )}

        <div className="flex items-center gap-2">
          <button
            onClick={handleDecapsulate}
            disabled={!ciphertext}
            className="flex items-center gap-2 px-4 py-2 bg-green-600 hover:bg-green-700 disabled:opacity-40 disabled:cursor-not-allowed text-white text-sm font-medium rounded-lg transition-colors"
          >
            <Unlock size={14} />
            Desencapsular
          </button>
          <button
            onClick={handleReset}
            className="flex items-center gap-2 px-4 py-2 border border-slate-300 dark:border-slate-600 text-slate-600 dark:text-slate-300 hover:bg-slate-50 dark:hover:bg-slate-700 text-sm font-medium rounded-lg transition-colors"
          >
            <RefreshCw size={14} />
            Reiniciar
          </button>
          {!ciphertext && (
            <span className="text-xs text-amber-600 dark:text-amber-400">
              Encapsula un mensaje primero
            </span>
          )}
        </div>
      </StepCard>

      {/* Educational note */}
      <div className="bg-slate-50 dark:bg-slate-800/50 rounded-xl p-5 border border-slate-200 dark:border-slate-700 text-sm text-slate-600 dark:text-slate-400">
        <p className="font-semibold text-slate-700 dark:text-slate-300 mb-2">📚 Nota Educativa</p>
        <p>
          Este simulador usa <code className="bg-slate-200 dark:bg-slate-700 px-1 rounded">q={Q}</code> y
          vectores de dimensión 2 para ilustrar el concepto. El estándar ML-KEM-768 real usa
          polinomios de grado 255 en anillos <code className="bg-slate-200 dark:bg-slate-700 px-1 rounded">R_q = Z_3329[x]/(x^256+1)</code>,
          módulo <code className="bg-slate-200 dark:bg-slate-700 px-1 rounded">q=3329</code> y
          módulos de dimensión 3, proporcionando 178 bits de seguridad cuántica.
        </p>
      </div>
    </div>
  );
};

export default MLKEMSimulator;
